[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Packages.pcov",
  "php82Packages.xdebug",
  "mysql",
  "nodejs"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:cache || true",
  "php artisan migrate --force || true"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
